language: python
python:
  - 2.7
  - 3.4

notifications:
  email: false
 
sudo: false

# Setup anaconda
# adapted from
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
# https://gist.github.com/dan-blanchard/7045057
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda

# Install packages
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy matplotlib nose scipy pep8 cython
  - source activate env_name
  - python setup.py install

script:
- python tests.py
